use cape_codd;
SELECT SKU,SKU_DESCRIPTION FROM INVENTORY;
SELECT SKU_Description, SKU FROM INVENTORY;
SELECT WarehouseID FROM INVENTORY;
SELECT DISTINCT WarehouseID FROM INVENTORY;
SELECT * from INVENTORY WHERE QUANTITYONHAND > 0;
SELECT SKU,SKU_DESCRIPTION FROM INVENTORY WHERE Quantity = 0 order by warehouseID asc;


